blank_issues_enabled: false
contact_links:
  - name: Q&A
    url: https://github.com/dippi9845/PJ/discussions/27
    about: Please ask and answer questions here.
  - name: Possible Bug
    url: https://github.com/dippi9845/PJ/discussions/22
    about: If you think that a bug is present
  - name: Possible feature
    url: https://github.com/dippi9845/PJ/discussions/20
    about: If you think that need to be added something, first discuss here
